# 基础镜像
FROM redis
# author
MAINTAINER wms

# 挂载目录
VOLUME /home/wms/redis
# 创建目录
RUN mkdir -p /home/wms/redis
# 指定路径
WORKDIR /home/wms/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/wms/redis/redis.conf
