import { fromPairs } from 'lodash'

export * from './auth.service'
export * from './materialIn.service'
export * from './binIn.service'
export * from './plant.service'
export * from './receiveMaterial.service'
export * from './kanban.service'
export * from './wareShift.service'
export * from './materialCall.service'
export * from './manualTrans.service'
export * from './material.service'
export * from './stock.service'
export * from './IQC.service'
export * from './splitPallet.service'