# 基础镜像
FROM adoptopenjdk/openjdk8-openj9:alpine-slim
# author
MAINTAINER wms

# 挂载目录
VOLUME /home/wms
# 创建目录
RUN mkdir -p /home/wms
# 安装字体
RUN yum install dejavu-sans-fonts fontconfig -y
# 指定路径
WORKDIR /home/wms
# 复制jar文件到路径
COPY ./jar/wms-modules-reservation.jar /home/wms/wms-modules-reservation.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","wms-modules-reservation.jar"]