# 基础镜像
FROM nginx
# author
MAINTAINER wms

# 挂载目录
VOLUME /home/wms/projects/wms-ui
# 创建目录
RUN mkdir -p /home/wms/projects/wms-ui
# 指定路径
WORKDIR /home/wms/projects/wms-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/wms/projects/wms-ui
