# 基础镜像
FROM adoptopenjdk/openjdk8-openj9:alpine-slim
# author
MAINTAINER wms

# 挂载目录
VOLUME /home/wms
# 创建目录
RUN mkdir -p /home/wms
# 指定路径
WORKDIR /home/wms
# 复制jar文件到路径
COPY ./jar/wms-auth.jar /home/wms/wms-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=dev","wms-auth.jar"]